config/routes.rb
Rails.application.routes.draw do
  resources :balance_sheets
  resources :equities

  root 'equities#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/balance_sheet.rb
class BalanceSheet < ApplicationRecord
  has_many :equities
end

app/models/equity.rb
class Equity < ApplicationRecord
  belongs_to :balance_sheet, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/balance_sheets_controller.rb
class BalanceSheetsController < ApplicationController
  before_action :set_balance_sheet, only: [:show, :edit, :update, :destroy]

  # GET /balance_sheets
  # GET /balance_sheets.json
  def index
    @balance_sheet = Equity.all
  end

  # GET /balance_sheets/1
  # GET /balance_sheets/1.json
  def show
  end

  # GET /balance_sheets/new
  def new
    @balance_sheet = BalanceSheet.new
  end

  # GET /balance_sheets/1/edit
  def edit
  end

  # POST /balance_sheets
  # POST /balance_sheets.json
  def create
    @balance_sheet = BalanceSheet.new(balance_sheet_params)

    respond_to do |format|
      if @balance_sheet.save
        format.html { redirect_to @balance_sheet, notice: 'Balance sheet was successfully created.' }
        format.json { render :show, status: :created, location: @balance_sheet }
      else
        format.html { render :new }
        format.json { render json: @balance_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /balance_sheets/1
  # PATCH/PUT /balance_sheets/1.json
  def update
    respond_to do |format|
      if @balance_sheet.update(balance_sheet_params)
        format.html { redirect_to @balance_sheet, notice: 'Balance sheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @balance_sheet }
      else
        format.html { render :edit }
        format.json { render json: @balance_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /balance_sheets/1
  # DELETE /balance_sheets/1.json
  def destroy
    @balance_sheet.destroy
    respond_to do |format|
      format.html { redirect_to balance_sheets_url, notice: 'Balance sheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_balance_sheet
      @balance_sheet = BalanceSheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def balance_sheet_params
      params.fetch(:balance_sheet, {})
    end
end

app/controllers/equities_controller.rb
class EquitiesController < ApplicationController
  before_action :set_equity, only: [:show, :edit, :update, :destroy]

  # GET /equities
  # GET /equities.json
  def index
    @equities = Equity.all
  end

  # GET /equities/1
  # GET /equities/1.json
  def show
  end

  # GET /equities/new
  def new
    @equity = Equity.new
  end

  # GET /equities/1/edit
  def edit
  end

  # POST /equities
  # POST /equities.json
  def create
    @equity = Equity.new(equity_params)
    respond_to do |format|
      if @equity.save
        format.html { redirect_to @equity, notice: 'Equity was successfully created.' }
        format.json { render :show, status: :created, location: @equity }
      else
        format.html { render :new }
        format.json { render json: @equity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equities/1
  # PATCH/PUT /equities/1.json
  def update
    respond_to do |format|
      if @equity.update(equity_params)
        format.html { redirect_to @equity, notice: 'Equity was successfully updated.' }
        format.json { render :show, status: :ok, location: @equity }
      else
        format.html { render :edit }
        format.json { render json: @equity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equities/1
  # DELETE /equities/1.json
  def destroy
    @equity.destroy
    respond_to do |format|
      format.html { redirect_to equities_url, notice: 'Equity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equity
      @equity = Equity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equity_params
      params.require(:equity).permit(:name,:ask,:bid,:percent_change,:shares_owned,:price_paid,:symbol)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balance_sheets_helper.rb
module BalanceSheetsHelper
end

app/helpers/equities_helper.rb
module EquitiesHelper
end

app/views/balance_sheets/_form.html.erb
<%= form_for(balance_sheet) do |f| %>
  <% if balance_sheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(balance_sheet.errors.count, "error") %> prohibited this balance_sheet from being saved:</h2>

      <ul>
      <% balance_sheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/balance_sheets/edit.html.erb
<h1>Editing Balance Sheet</h1>

<%= render 'form', balance_sheet: @balance_sheet %>

<%= link_to 'Show', @balance_sheet %> |
<%= link_to 'Back', balance_sheets_path %>

app/views/balance_sheets/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1>Balance Sheet</h1>

    <table class="table">
      <thead>
        <tr>
          <th> Date </th>
          <th> Name </th>
          <th> Price Entered </th>
          <th> Shares owned</th>
          <th> Closing Price </th>
          <th> Current Profit / Loss </th>
          <th> Charts </th>
        </tr>
      </thead>
      <tbody>
        <% @balance_sheet.each do |equity| %>
        <% data = YahooFinance::Client.new%>
        <% equity_data = data.quotes([equity.symbol],[:ask,:name,:open,:close,:previous_close,:change_in_percent])%>
        <tr>
        <td><%= equity.updated_at.localtime.strftime("%m/%d/%Y %I:%M%P")%></td>
        <td><%= equity_data[0].name%></td>
        <td><%= equity.price_paid%></td>
        <td><%= equity.shares_owned %></td>
        <td><%= equity_data[0].close%></td>
        <td><%= (equity_data[0].close.to_f - (equity.price_paid.to_f * equity.shares_owned.to_f)).round(2) %></td>
        <td><%= link_to equity.symbol, "https://sg.finance.yahoo.com/chart/#{equity.symbol}", class: "btn btn-outline-warning"%></td>
        <td><%= link_to 'Edit', edit_equity_path(equity) %></td>
        <td><%= link_to 'Destroy', equity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>

      </tbody>

    </table>


<br>

<%= link_to 'Back to Home', equities_path, class: "btn btn-outline-success" %>

app/views/balance_sheets/new.html.erb
<h1>New Balance Sheet</h1>

<%= render 'form', balance_sheet: @balance_sheet %>

<%= link_to 'Back', balance_sheets_path %>

app/views/balance_sheets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_balance_sheet_path(@balance_sheet) %> |
<%= link_to 'Back', balance_sheets_path %>

app/views/equities/_form.html.erb
<div class="container">
  <%= bootstrap_form_for(equity) do |f| %>
  <% if equity.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(equity.errors.count, "error") %>
      prohibited this equity from being saved:</h2>

    <ul>
      <% equity.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="field">
    <%= f.text_field :symbol %>
  </div>
  <div class="field">
    <%= f.text_field :shares_owned %>
  </div>

  <div class="field">
    <%= f.text_field :price_paid %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
  <br />
  <%= link_to 'Back', equities_path, class: "btn btn-danger" %>
  <% end %>
</div>

app/views/equities/edit.html.erb
<h1>Editing Equity</h1>

<%= render 'form', equity: @equity %>

<%= link_to 'Show', @equity %> |
<%= link_to 'Back', equities_path %>

app/views/equities/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1>Equities</h1>

    <table class="table">
      <thead>
        <tr>
          <th> Symbol </th>
          <th> Name </th>
          <th> Open </th>
          <th> Close </th>
          <th> Previous Close </th>
          <th> % change</th>
          <th> Shares owned</th>
          <th> Price paid</th>
        </tr>
      </thead>
      <tbody>
        <% @equities.each do |equity| %>
        <% data = YahooFinance::Client.new%>
        <% equity_data = data.quotes([equity.symbol],[:ask,:name,:open,:close,:previous_close,:change_in_percent])%>
        <tr>
        <td><%= equity.symbol %></td>
        <td><%= equity_data[0].name%></td>
        <td><%= equity_data[0].open%></td>
        <td><%= equity_data[0].close%></td>
        <td><%= equity_data[0].previous_close%></td>
        <td><%= equity_data[0].change_in_percent%></td>
        <td><%= equity.shares_owned %></td>
        <td><%= equity.price_paid %></td>
        <td><%= link_to 'Edit', edit_equity_path(equity) %></td>
        <td><%= link_to 'Destroy', equity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>

      </tbody>

    </table>


<br>

<%= link_to 'New Equity', new_equity_path, class: "btn btn-outline-success" %>
<span>&nbsp;&nbsp;&nbsp;</span>
<%= link_to "Check Balance Sheet", balance_sheets_path, class: "btn btn-outline-danger" %>
</div>

app/views/equities/new.html.erb
<br />
<br />
<div class="container">
  <h1>New Equity</h1>

  <%= render 'form', equity: @equity %>

</div>

app/views/equities/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_equity_path(@equity) %> |
<%= link_to 'Back', equities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>